name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs every day 7am est
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in SDET Unicorns posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://sdetunicorns.com/feed/"
